#!/bin/sh
apt-get install git
atp-get install pip
pip install markdown2
cd /home/$USER && git clone https://github.com/voidcode/.howtoapp-courses.git
cd /home/$USER && git clone https://github.com/voidcode/howtoapp.git
cd /home/$USER/howtoapp/ && chmod +x run && ./run
