#!/bin/sh
apt-get install git
atp-get install pip
pip install python-markdown
cd $HOME && git clone https://github.com/voidcode/.howtoapp-courses.git
cd $HOME && git clone git@github.com:voidcode/howtoapp.git
python main.py